### ISSUE TITLE
Failing tests on Windows with node 0.12.7

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/tilelive-vector#103]
related? https://github.com/mapbox/tilelive-bridge/issues/52

:x: There are failing tests with node **0.12.7:**

https://ci.appveyor.com/project/Mapbox/tilelive-vector/build/1.0.191/job/2de40a9mp4sb0fve#L994

![image](https://cloud.githubusercontent.com/assets/4549888/9061180/3bf7e54c-3aba-11e5-8707-0f19e0b5fc7e.png)

----------

:white_check_mark: Same tests work ok with node **0.10.40**

https://ci.appveyor.com/project/Mapbox/tilelive-vector/build/1.0.191/job/pevsqguap2wct5t0#L995

![image](https://cloud.githubusercontent.com/assets/4549888/9061208/748fb09c-3aba-11e5-8b2a-60cdc9eff861.png)

**Comment by BergWerkGIS** [comment]
Same error on Linux:
https://travis-ci.org/mapbox/tilelive-vector/jobs/75961415#L627

Probably [buf.writeUInt8](https://nodejs.org/api/buffer.html#buffer_buf_writeuint8_value_offset_noassert) is faulty in 0.12., will investigate.

Used in `function replacer`:
https://github.com/mapbox/tilelive-vector/blob/master/test/backend.js#L172

**Comment by BergWerkGIS** [comment]
@springmeyer @flippmoke 

Test is failing with 0.12, because parameter `value` passed to [`function replacer`](https://github.com/mapbox/tilelive-vector/blob/master/test/backend.js#L168-L177) is different than with 0.10.

Parameter `value` is created [here via `JSON.parse(JSON.stringify(vtile.toJSON(), replacer))`](https://github.com/mapbox/tilelive-vector/blob/master/test/backend.js#L141)

### parameter `value` with node 0.10.40 (just an array)

```
[ 255, 216, ..., 255, 217 ]
```

### parameter `value`with node 0.12.7 (an object)

```
{ type: 'Buffer',
  data: [ 255, 216, ..., 255, 217 ]
}
```

Still has to be determined what is responsible for that?

* `JSON.parse`? 
* `JSON.stringify`?
* `vtile.toJSON`?

Your turn, or my turn?

--- 

Dirty (works on my machine) hack would be in `replacer`:

```
if (node=0.12) value = value.data
```

**Comment by flippmoke** [comment]
My guess is that it has something to do with `NanNewBufferHandle` here: https://github.com/mapnik/node-mapnik/blob/master/src/mapnik_vector_tile.cpp#L1718 I will look into it more.

**Comment by BergWerkGIS** [comment]
@flippmoke one question:

Your change fixes the tests, but shouldn't that be taken care of in the native code, so that the API is consistent across node versions?
Isn't that a breaking change for other modules, if the format of the GeoJSON changes?

Or better not fiddle with the new implementation of `NanNewBufferHandle`?


### `vtile.toJSON()` 0.10

```
[
  {
    "name": "_image",
    "extent": 4096,
    "version": 1,
    "features": [
      {
        "raster": {
          "type": "Buffer",
          "data": [
            255,
            216,
            ...,
            255,
            217
          ]
        },
        "type": 0,
        "geometry": []
      }
    ]
  }
]
```

### `vtile.toJSON()` 0.12

```
[
  {
    "name": "_image",
    "extent": 4096,
    "version": 1,
    "features": [
      {
        "raster": [
          255,
          216,
          ...,
          255,
          217
        ],
        "type": 0,
        "geometry": []
      }
    ]
  }
]
```
