### ISSUE TITLE
Split out tm2z and xray functionality

### ISSUE THREAD

**Issue by springmeyer** [mapbox/tilelive-vector#124]
I keep on noticing the `tm2z` and `xray` functionality and feeling like these should be their own `tilelive-tm2z` and `tilelive-xray` modules.

Happy to stop having this itch if @yhahn or @rclark can tell me a good reason they are part of tilelive-vector. But from my perspective `tilelive-vector` should be about only `vtile` -> `image` and other functionality should be separate.

This came up just now because I notice that `mapbox-tile-copy` depends on `tilelive-vector` but only for the `tm2z` support and not for anything to do with rendering images.

/cc @mapsam

**Comment by yhahn** [comment]
No -- we could split these out but just make a longer chain of dependencies. These are all fairly interdependent at this point. No more itching : )

```
tm2z => vector => vector/Backend
xray => vector => vector/Backend
```
