### ISSUE TITLE
missing return cb

### ISSUE THREAD

**Issue by springmeyer** [mapbox/tilelive-vector#89]
Not sure if this is a problem, but why trying to replicate https://github.com/mapbox/mapbox-studio/issues/1047 (callbacks called more than once) I noticed that tl-vector consistently uses `return cb` except in this one place:

```diff
diff --git a/index.js b/index.js
index 587357d..4741c23 100644
--- a/index.js
+++ b/index.js
@@ -414,7 +414,7 @@ function tm2z(uri, callback) {
     var unpacked = false;
 
     var once = 0;
-    var error = function(err) { if (!once++) callback(err); };
+    var error = function(err) { if (!once++) return callback(err); };
 
     // Check for unpacked manifest
     exists(base + '/.unpacked', function(exists) {
```

**Comment by springmeyer** [comment]
noting I also see `return` not used with the callbacks at https://github.com/mapbox/node-get/blob/43cae553f4335a7ab3963772d7fef8a86e439725/lib/index.js#L294-L295 and https://github.com/mapbox/node-get/blob/43cae553f4335a7ab3963772d7fef8a86e439725/lib/index.js#L315-L316

**Comment by yhahn** [comment]
A return isn't necessary in all these cases -- each has a semaphore preventing multiple calls to the callback and there's nothing else in this error function for a return to prevent.

**Comment by springmeyer** [comment]
thanks, closing.
